name: 'Create Pipeline Execution'
description: 'Create Cloud Manager Pipeline Execution'
inputs:
  programId:
    description: 'The Program ID'
    required: true
  environmentName:
    description: 'The Environment name'
    required: true
  action:
    description: 'create or delete'
    required: true
  imsOrgId:
    description: 'The IMS Organization ID'
    required: false
  clientId:
    description: 'When providing a JWT configuration, the client ID from the Adobe Developer Console'
    required: false
  clientSecret:
    description: 'When providing a JWT configuration, the client secret from the Adobe Developer Console'
    required: false
  technicalAccountId:
    description: 'When providing a JWT configuration, the technical account email from the Adobe Developer Console'
    required: false
  key:
    description: 'When providing a JWT configuration, the private key for the technical account'
    required: false
  imsConfig:
    description: 'IMS config object'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
